version: '3'

services:
  minio:
    image: docker.io/bitnami/minio:2023
    ports:
      - '9010:9000'
      - '9011:9001'
    environment:
      - MINIO_ROOT_USER=username
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=bucket

  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 2017:5432
    volumes:
      - ./etc/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: always
      
