// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pgapi

import (
	"github.com/jackc/pgx/v5/pgtype"
	"oj/element/gradient"
)

type Attempt struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	QuizID    pgtype.Int8
	UserID    pgtype.Int8
}

type Bot struct {
	ID          int64
	CreatedAt   pgtype.Timestamptz
	OwnerID     pgtype.Int8
	AssistantID pgtype.Text
	Name        pgtype.Text
	Description pgtype.Text
	Published   pgtype.Bool
}

type Code struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Code      pgtype.Text
	Nonce     pgtype.Text
	Email     pgtype.Text
}

type Delivery struct {
	ID          int64
	CreatedAt   pgtype.Timestamptz
	MessageID   pgtype.Int8
	RoomID      pgtype.Int8
	RecipientID pgtype.Int8
	SenderID    pgtype.Int8
	SentAt      pgtype.Timestamptz
}

type Friend struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	AID       pgtype.Int8
	BID       pgtype.Int8
	BRole     pgtype.Text
}

type Gradient struct {
	ID        int64
	CreatedAt pgtype.Text
	UserID    pgtype.Int8
	Gradient  gradient.Gradient
}

type Image struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Url       pgtype.Text
	UserID    pgtype.Int8
}

type KidsCode struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Code      pgtype.Text
	Nonce     pgtype.Text
	UserID    pgtype.Int8
}

type KidsParent struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	KidID     pgtype.Int8
	ParentID  pgtype.Int8
}

type Message struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	SenderID  pgtype.Int8
	RoomID    pgtype.Int8
	Body      pgtype.Text
}

type MigrationVersion struct {
	Version pgtype.Int8
}

type Note struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	OwnerID   pgtype.Int8
	Body      pgtype.Text
	Published pgtype.Bool
}

type Postcard struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Sender    pgtype.Int8
	Recipient pgtype.Int8
	Subject   pgtype.Text
	Body      pgtype.Text
	State     pgtype.Text
}

type Question struct {
	ID        int64
	CreatedAt pgtype.Text
	QuizID    pgtype.Int8
	Text      pgtype.Text
	Answer    pgtype.Text
}

type Quiz struct {
	ID          int64
	CreatedAt   pgtype.Timestamptz
	Name        pgtype.Text
	Description pgtype.Text
	Published   pgtype.Bool
}

type Response struct {
	ID         int64
	CreatedAt  pgtype.Timestamptz
	QuizID     pgtype.Int8
	UserID     pgtype.Int8
	AttemptID  pgtype.Int8
	QuestionID pgtype.Int8
	Text       pgtype.Text
}

type Room struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Key       pgtype.Text
}

type RoomUser struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	RoomID    pgtype.Int8
	UserID    pgtype.Int8
}

type Session struct {
	ID     int64
	UserID pgtype.Int8
	Key    pgtype.Text
}

type Thread struct {
	ID          int64
	CreatedAt   pgtype.Timestamptz
	ThreadID    pgtype.Text
	AssistantID pgtype.Text
	UserID      pgtype.Int8
}

type User struct {
	ID           int64
	CreatedAt    pgtype.Timestamptz
	Username     pgtype.Text
	Email        pgtype.Text
	AvatarURL    pgtype.Text
	IsParent     pgtype.Bool
	Bio          pgtype.Text
	BecomeUserID pgtype.Int8
	Admin        pgtype.Bool
}
