// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: bot_messages.sql

package api

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBotMessage = `-- name: CreateBotMessage :one
insert into bot_messages(thread_id, role, content) values($1,$2,$3) returning id, created_at, thread_id, role, content
`

type CreateBotMessageParams struct {
	ThreadID pgtype.Int8
	Role     string
	Content  string
}

func (q *Queries) CreateBotMessage(ctx context.Context, arg CreateBotMessageParams) (BotMessage, error) {
	row := q.db.QueryRow(ctx, createBotMessage, arg.ThreadID, arg.Role, arg.Content)
	var i BotMessage
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ThreadID,
		&i.Role,
		&i.Content,
	)
	return i, err
}

const threadMessages = `-- name: ThreadMessages :many
select id, created_at, thread_id, role, content from bot_messages where thread_id = $1 order by created_at asc
`

func (q *Queries) ThreadMessages(ctx context.Context, threadID pgtype.Int8) ([]BotMessage, error) {
	rows, err := q.db.Query(ctx, threadMessages, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotMessage
	for rows.Next() {
		var i BotMessage
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ThreadID,
			&i.Role,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
