// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deliveries.sql

package api

import (
	"context"
)

const delivery = `-- name: Delivery :one
select id, created_at, message_id, room_id, recipient_id, sender_id, sent_at from deliveries where id = $1
`

func (q *Queries) Delivery(ctx context.Context, id int64) (Delivery, error) {
	row := q.db.QueryRow(ctx, delivery, id)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.MessageID,
		&i.RoomID,
		&i.RecipientID,
		&i.SenderID,
		&i.SentAt,
	)
	return i, err
}
