// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: friends.sql

package api

import (
	"context"
)

const createFriend = `-- name: CreateFriend :one
insert into friends(a_id, b_id, b_role) values($1, $2, $3) returning id, created_at, a_id, b_id, b_role
`

type CreateFriendParams struct {
	AID   int64
	BID   int64
	BRole string
}

func (q *Queries) CreateFriend(ctx context.Context, arg CreateFriendParams) (Friend, error) {
	row := q.db.QueryRow(ctx, createFriend, arg.AID, arg.BID, arg.BRole)
	var i Friend
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.AID,
		&i.BID,
		&i.BRole,
	)
	return i, err
}
