// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: gradients.sql

package api

import (
	"context"

	"oj/gradient"
)

const insertGradient = `-- name: InsertGradient :one
insert into gradients(user_id, gradient) values($1, $2) returning id, created_at, user_id, gradient
`

type InsertGradientParams struct {
	UserID   int64
	Gradient gradient.Gradient
}

func (q *Queries) InsertGradient(ctx context.Context, arg InsertGradientParams) (Gradient, error) {
	row := q.db.QueryRow(ctx, insertGradient, arg.UserID, arg.Gradient)
	var i Gradient
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.Gradient,
	)
	return i, err
}
