// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: kids_parents.sql

package api

import (
	"context"
)

const createKidParent = `-- name: CreateKidParent :one
insert into kids_parents(kid_id, parent_id) values($1, $2) returning id, created_at, kid_id, parent_id
`

type CreateKidParentParams struct {
	KidID    int64
	ParentID int64
}

func (q *Queries) CreateKidParent(ctx context.Context, arg CreateKidParentParams) (KidsParent, error) {
	row := q.db.QueryRow(ctx, createKidParent, arg.KidID, arg.ParentID)
	var i KidsParent
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.KidID,
		&i.ParentID,
	)
	return i, err
}
