// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package api

import (
	"github.com/jackc/pgx/v5/pgtype"
	"oj/avatar"
	"oj/gradient"
)

type Attempt struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	QuizID    int64
	UserID    int64
}

type Bot struct {
	ID          int64
	CreatedAt   pgtype.Timestamptz
	OwnerID     int64
	AssistantID string
	Name        string
	Description string
	Published   bool
}

type Code struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Code      string
	Nonce     string
	Email     string
}

type Delivery struct {
	ID          int64
	CreatedAt   pgtype.Timestamptz
	MessageID   int64
	RoomID      int64
	RecipientID int64
	SenderID    int64
	SentAt      pgtype.Timestamptz
}

type Friend struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	AID       int64
	BID       int64
	BRole     string
}

type Gradient struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	UserID    int64
	Gradient  gradient.Gradient
}

type Image struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Url       string
	UserID    int64
}

type KidsCode struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Code      string
	Nonce     string
	UserID    int64
}

type KidsParent struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	KidID     int64
	ParentID  int64
}

type Message struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	SenderID  int64
	RoomID    int64
	Body      string
}

type Note struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	OwnerID   int64
	Body      string
	Published bool
}

type Postcard struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Sender    int64
	Recipient int64
	Subject   string
	Body      string
	State     string
}

type Question struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	QuizID    int64
	Text      string
	Answer    string
}

type Quiz struct {
	ID          int64
	CreatedAt   pgtype.Timestamptz
	Name        string
	Description string
	Published   bool
	UserID      int64
}

type Response struct {
	ID         int64
	CreatedAt  pgtype.Timestamptz
	QuizID     int64
	UserID     int64
	AttemptID  int64
	QuestionID int64
	Text       string
}

type Room struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Key       string
}

type RoomUser struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	RoomID    int64
	UserID    int64
}

type Session struct {
	ID     int64
	UserID int64
	Key    string
}

type Thread struct {
	ID          int64
	CreatedAt   pgtype.Timestamptz
	ThreadID    string
	AssistantID string
	UserID      int64
}

type User struct {
	ID                  int64
	CreatedAt           pgtype.Timestamptz
	Username            string
	Email               pgtype.Text
	AvatarUrlDeprecated string
	IsParent            bool
	Bio                 string
	BecomeUserID        pgtype.Int8
	Admin               bool
	Gradient            gradient.Gradient
	Avatar              avatar.Avatar
}
