// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package api

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	"oj/avatar"
	"oj/gradient"
)

type RiverJobState string

const (
	RiverJobStateAvailable RiverJobState = "available"
	RiverJobStateCancelled RiverJobState = "cancelled"
	RiverJobStateCompleted RiverJobState = "completed"
	RiverJobStateDiscarded RiverJobState = "discarded"
	RiverJobStatePending   RiverJobState = "pending"
	RiverJobStateRetryable RiverJobState = "retryable"
	RiverJobStateRunning   RiverJobState = "running"
	RiverJobStateScheduled RiverJobState = "scheduled"
)

func (e *RiverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiverJobState(s)
	case string:
		*e = RiverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for RiverJobState: %T", src)
	}
	return nil
}

type NullRiverJobState struct {
	RiverJobState RiverJobState
	Valid         bool // Valid is true if RiverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.RiverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiverJobState), nil
}

type Attempt struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	QuizID    int64
	UserID    int64
}

type Bot struct {
	ID          int64
	CreatedAt   pgtype.Timestamptz
	OwnerID     int64
	AssistantID string
	Name        string
	Description string
	Published   bool
}

type ChessMatch struct {
	ID          int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	WhiteUserID int64
	BlackUserID int64
	Pgn         string
}

type Code struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Code      string
	Nonce     string
	Email     string
}

type Delivery struct {
	ID          int64
	CreatedAt   pgtype.Timestamptz
	MessageID   int64
	RoomID      int64
	RecipientID int64
	SenderID    int64
	SentAt      pgtype.Timestamptz
}

type Friend struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	AID       int64
	BID       int64
	BRole     string
}

type Gradient struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	UserID    int64
	Gradient  gradient.Gradient
}

type Image struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Url       string
	UserID    int64
}

type KidsCode struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Code      string
	Nonce     string
	UserID    int64
}

type KidsParent struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	KidID     int64
	ParentID  int64
}

type Message struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	SenderID  int64
	RoomID    int64
	Body      string
}

type MusicTrack struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	UserID    int64
	Url       string
	Title     pgtype.Text
	Uploader  pgtype.Text
	Filename  string
	Status    string
	Error     pgtype.Text
}

type Note struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	OwnerID   int64
	Body      string
	Published bool
}

type Postcard struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Sender    int64
	Recipient int64
	Subject   string
	Body      string
	State     string
}

type Question struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	QuizID    int64
	Text      string
	Answer    string
}

type Quiz struct {
	ID          int64
	CreatedAt   pgtype.Timestamptz
	Name        string
	Description string
	Published   bool
	UserID      int64
	IsDeleted   bool
}

type Response struct {
	ID         int64
	CreatedAt  pgtype.Timestamptz
	QuizID     int64
	UserID     int64
	AttemptID  int64
	QuestionID int64
	Text       string
}

type RiverClient struct {
	ID        string
	CreatedAt pgtype.Timestamptz
	Metadata  []byte
	PausedAt  pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RiverClientQueue struct {
	RiverClientID    string
	Name             string
	CreatedAt        pgtype.Timestamptz
	MaxWorkers       int64
	Metadata         []byte
	NumJobsCompleted int64
	NumJobsRunning   int64
	UpdatedAt        pgtype.Timestamptz
}

type RiverJob struct {
	ID           int64
	State        RiverJobState
	Attempt      int16
	MaxAttempts  int16
	AttemptedAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	FinalizedAt  pgtype.Timestamptz
	ScheduledAt  pgtype.Timestamptz
	Priority     int16
	Args         []byte
	AttemptedBy  []string
	Errors       [][]byte
	Kind         string
	Metadata     []byte
	Queue        string
	Tags         []string
	UniqueKey    []byte
	UniqueStates pgtype.Bits
}

type RiverLeader struct {
	ElectedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	LeaderID  string
	Name      string
}

type RiverMigration struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Version   int64
}

type RiverQueue struct {
	Name      string
	CreatedAt pgtype.Timestamptz
	Metadata  []byte
	PausedAt  pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Room struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Key       string
}

type RoomUser struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	RoomID    int64
	UserID    int64
}

type Session struct {
	ID     int64
	UserID int64
	Key    string
}

type Thread struct {
	ID          int64
	CreatedAt   pgtype.Timestamptz
	ThreadID    string
	AssistantID string
	UserID      int64
}

type User struct {
	ID                  int64
	CreatedAt           pgtype.Timestamptz
	Username            string
	Email               pgtype.Text
	AvatarUrlDeprecated string
	IsParent            bool
	Bio                 string
	BecomeUserID        pgtype.Int8
	Admin               bool
	Gradient            gradient.Gradient
	Avatar              avatar.Avatar
}
