// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: music_tracks.sql

package api

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMusicTrack = `-- name: InsertMusicTrack :one
insert into music_tracks(user_id, url, title, uploader, filename, status, error)
values($1, $2, $3, $4, $5, $6, $7)
returning id, created_at, user_id, url, title, uploader, filename, status, error
`

type InsertMusicTrackParams struct {
	UserID   int64
	Url      string
	Title    pgtype.Text
	Uploader pgtype.Text
	Filename string
	Status   string
	Error    pgtype.Text
}

func (q *Queries) InsertMusicTrack(ctx context.Context, arg InsertMusicTrackParams) (MusicTrack, error) {
	row := q.db.QueryRow(ctx, insertMusicTrack,
		arg.UserID,
		arg.Url,
		arg.Title,
		arg.Uploader,
		arg.Filename,
		arg.Status,
		arg.Error,
	)
	var i MusicTrack
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.Url,
		&i.Title,
		&i.Uploader,
		&i.Filename,
		&i.Status,
		&i.Error,
	)
	return i, err
}

const updateMusicTrack = `-- name: UpdateMusicTrack :exec
update music_tracks set title = $1, uploader = $2, status = $3, error = $4
where user_id = $5 and filename = $6
`

type UpdateMusicTrackParams struct {
	Title    pgtype.Text
	Uploader pgtype.Text
	Status   string
	Error    pgtype.Text
	UserID   int64
	Filename string
}

func (q *Queries) UpdateMusicTrack(ctx context.Context, arg UpdateMusicTrackParams) error {
	_, err := q.db.Exec(ctx, updateMusicTrack,
		arg.Title,
		arg.Uploader,
		arg.Status,
		arg.Error,
		arg.UserID,
		arg.Filename,
	)
	return err
}

const userMusicTracks = `-- name: UserMusicTracks :many
select id, created_at, user_id, url, title, uploader, filename, status, error from music_tracks where user_id = $1 order by created_at desc
`

func (q *Queries) UserMusicTracks(ctx context.Context, userID int64) ([]MusicTrack, error) {
	rows, err := q.db.Query(ctx, userMusicTracks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MusicTrack
	for rows.Next() {
		var i MusicTrack
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.Uploader,
			&i.Filename,
			&i.Status,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
