// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: quizzes.sql

package api

import (
	"context"
)

const allQuizzes = `-- name: AllQuizzes :many
select id, created_at, name, description, published, user_id from quizzes order by created_at desc
`

func (q *Queries) AllQuizzes(ctx context.Context) ([]Quiz, error) {
	rows, err := q.db.Query(ctx, allQuizzes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quiz
	for rows.Next() {
		var i Quiz
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Name,
			&i.Description,
			&i.Published,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createQuiz = `-- name: CreateQuiz :one
insert into quizzes(name,description,user_id) values($1,$2,$3) returning id, created_at, name, description, published, user_id
`

type CreateQuizParams struct {
	Name        string
	Description string
	UserID      int64
}

func (q *Queries) CreateQuiz(ctx context.Context, arg CreateQuizParams) (Quiz, error) {
	row := q.db.QueryRow(ctx, createQuiz, arg.Name, arg.Description, arg.UserID)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Description,
		&i.Published,
		&i.UserID,
	)
	return i, err
}

const publishedQuizzes = `-- name: PublishedQuizzes :many
select id, created_at, name, description, published, user_id from quizzes where published = true order by created_at desc
`

func (q *Queries) PublishedQuizzes(ctx context.Context) ([]Quiz, error) {
	rows, err := q.db.Query(ctx, publishedQuizzes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quiz
	for rows.Next() {
		var i Quiz
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Name,
			&i.Description,
			&i.Published,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishedUserQuizzes = `-- name: PublishedUserQuizzes :many
select id, created_at, name, description, published, user_id from quizzes where published = true and user_id = $1 order by created_at desc
`

func (q *Queries) PublishedUserQuizzes(ctx context.Context, userID int64) ([]Quiz, error) {
	rows, err := q.db.Query(ctx, publishedUserQuizzes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quiz
	for rows.Next() {
		var i Quiz
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Name,
			&i.Description,
			&i.Published,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const questionCount = `-- name: QuestionCount :one
select count(*) from questions where quiz_id = $1
`

func (q *Queries) QuestionCount(ctx context.Context, quizID int64) (int64, error) {
	row := q.db.QueryRow(ctx, questionCount, quizID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const quiz = `-- name: Quiz :one
select id, created_at, name, description, published, user_id from quizzes where id = $1
`

func (q *Queries) Quiz(ctx context.Context, id int64) (Quiz, error) {
	row := q.db.QueryRow(ctx, quiz, id)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Description,
		&i.Published,
		&i.UserID,
	)
	return i, err
}

const setQuizPublished = `-- name: SetQuizPublished :one
update quizzes set published = $1 where id = $2 returning id, created_at, name, description, published, user_id
`

type SetQuizPublishedParams struct {
	Published bool
	ID        int64
}

func (q *Queries) SetQuizPublished(ctx context.Context, arg SetQuizPublishedParams) (Quiz, error) {
	row := q.db.QueryRow(ctx, setQuizPublished, arg.Published, arg.ID)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Description,
		&i.Published,
		&i.UserID,
	)
	return i, err
}

const updateQuiz = `-- name: UpdateQuiz :one
update quizzes set name = $1, description = $2 where id = $3 returning id, created_at, name, description, published, user_id
`

type UpdateQuizParams struct {
	Name        string
	Description string
	ID          int64
}

func (q *Queries) UpdateQuiz(ctx context.Context, arg UpdateQuizParams) (Quiz, error) {
	row := q.db.QueryRow(ctx, updateQuiz, arg.Name, arg.Description, arg.ID)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Description,
		&i.Published,
		&i.UserID,
	)
	return i, err
}
