// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: room_users.sql

package api

import (
	"context"
)

const createRoomUser = `-- name: CreateRoomUser :one
insert into room_users(room_id, user_id) values($1, $2) returning id, created_at, room_id, user_id
`

type CreateRoomUserParams struct {
	RoomID int64
	UserID int64
}

func (q *Queries) CreateRoomUser(ctx context.Context, arg CreateRoomUserParams) (RoomUser, error) {
	row := q.db.QueryRow(ctx, createRoomUser, arg.RoomID, arg.UserID)
	var i RoomUser
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.RoomID,
		&i.UserID,
	)
	return i, err
}
