// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: rooms.sql

package api

import (
	"context"
)

const createRoom = `-- name: CreateRoom :one
insert into rooms(key) values($1) returning id, created_at, key
`

func (q *Queries) CreateRoom(ctx context.Context, key string) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom, key)
	var i Room
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Key)
	return i, err
}

const roomByKey = `-- name: RoomByKey :one
select id, created_at, key from rooms where key = $1
`

func (q *Queries) RoomByKey(ctx context.Context, key string) (Room, error) {
	row := q.db.QueryRow(ctx, roomByKey, key)
	var i Room
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Key)
	return i, err
}
