// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: threads.sql

package api

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const botThreads = `-- name: BotThreads :many
select id, created_at, thread_id, user_id, bot_id from threads where bot_id = $1 and user_id = $2
`

type BotThreadsParams struct {
	BotID  pgtype.Int8
	UserID int64
}

func (q *Queries) BotThreads(ctx context.Context, arg BotThreadsParams) ([]Thread, error) {
	rows, err := q.db.Query(ctx, botThreads, arg.BotID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thread
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ThreadID,
			&i.UserID,
			&i.BotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createThread = `-- name: CreateThread :one
insert into threads(user_id, thread_id, bot_id) values($1,$2,$3) returning id, created_at, thread_id, user_id, bot_id
`

type CreateThreadParams struct {
	UserID   int64
	ThreadID string
	BotID    pgtype.Int8
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error) {
	row := q.db.QueryRow(ctx, createThread, arg.UserID, arg.ThreadID, arg.BotID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ThreadID,
		&i.UserID,
		&i.BotID,
	)
	return i, err
}

const userThreadByID = `-- name: UserThreadByID :one
select id, created_at, thread_id, user_id, bot_id from threads where user_id = $1 and thread_id = $2
`

type UserThreadByIDParams struct {
	UserID   int64
	ThreadID string
}

func (q *Queries) UserThreadByID(ctx context.Context, arg UserThreadByIDParams) (Thread, error) {
	row := q.db.QueryRow(ctx, userThreadByID, arg.UserID, arg.ThreadID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ThreadID,
		&i.UserID,
		&i.BotID,
	)
	return i, err
}
