name: Test
run-name: Test (${{ github.actor }})
on:
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      minio:
        image: bitnamilegacy/minio:latest
        env:
          MINIO_ROOT_USER: username
          MINIO_ROOT_PASSWORD: password
          MINIO_DEFAULT_BUCKETS: bucket
        ports:
        - 9000:9000
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21.5'
      - run: |
          make test
